apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enterprise-ai-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deps.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
